language: java
sudo: true # use container based infrastructure
jdk:
- openjdk8
services:
  - postgresql
env:
    global:
        - TESTMODEL_URL=http://localhost:8080/intermine-demo
        - TESTMODEL_PATH=intermine-demo
before_install:
    - git clone https://github.com/intermine/ci-scripts
    - (cd ci-scripts && bash init-testmine.sh)
script:
    - python setup.py test
    - python setup.py livetest
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
